FROM python:3.8-slim-buster

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ADD requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ADD ./src .

CMD ["python3", "app.py"]