# Generated by Django 3.2.6 on 2021-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
